### PR TITLE
TLPORTAL-183 - sort faculty by order of importance

### PR DESCRIPTION
**Pull request by gsilver**
https://jira.it.umich.edu/browse/TLPORTAL-183

### CODE REVIEW

**Comment by dlhaines** [comment]
Could you add a list of disk files to the jira that can be used to test this?

**Comment by gsilver** [comment]
None of the disk files have the right combination of instructor types. Should I add a few as part of this branch?

**Comment by dlhaines** [comment]
Sounds good.

- Dave

On Fri, Mar 27, 2015 at 12:42 PM, Gonzalo Silverio <notifications@github.com

**Comment by gsilver** [comment]
Ok - done. I also corrected a bug (providentially revealed when I was testing with the testable file) :-)

**Pull request merged**
