### PR TITLE
Tlportal 230 - Move configuration of system check to security.yml file.

### PR DESCRIPTION
**Pull request by dlhaines**
Latte uses an existing user to perform a systems operations check.  This information should only be available in the security.yml file to ensure privacy.

### CODE REVIEW

**Comment by lsloan** [comment]
Looks pretty straightforward.  However, I think the changes are a little more than what the PR's title or description suggest.  It looks like code was refactored that wasn't involved with the move of secure configuration information.  The change is OK, but I don't understand why it was done.  The application had used `dataProviderCourse()` before, but it doesn't after.  I don't see any mention of that method anywhere else in the changes.  Is it still being used?

**Comment by dlhaines** [comment]
The call to dataProviderCourse is still used in courselist.rb.  

The change prompted some refactoring to keep implementation encapsulation intact.  The appropriate values for check_ uniqname and check_termid will depend on the source that the data provider is configured to use.  This means that their actual value is only relevant within the data provider implementation.  The dataProviderCheck call was added so that the information only relevant to a particular implementation would not leak out of the implementation class.

**Comment by lsloan** [comment]
I think I understand.  Nice job.

:shipit:

**Comment by zqian** [comment]
Looks good to me!

**Pull request merged**
