### PR TITLE
TLPORTAL-477: update buggy jruby-ssl (and include other minor updates).

### PR DESCRIPTION
**Pull request by dlhaines**

### CODE REVIEW

**Comment by sloanlance** [comment]
I read the project README.md because I was curious. Aside from the technical aspects, I thought the ECL-2.0 license is interesting. Does it apply to all we develop for U-M?

Also, I found the license's description at osedu.org is no longer available. In fact, the entire domain has changed hands. The README needs to be updated.

**Comment by lsloan** [comment]
I read the project README.md because I was curious. Aside from the technical aspects, I thought the ECL-2.0 license is interesting. Does it apply to all we develop for U-M?

Also, I found the license's description at osedu.org is no longer available. In fact, the entire domain has changed hands. The README needs to be updated.

**Comment by arwhyte** [comment]
This URL works: https://opensource.org/licenses/ECL-2.0

ECL-2.0 was developed for the Sakai Project based on concerns raised by Berkeley regarding patent claims that might be made against their patent portfolio.  It's a near line-for-line copy of the Apache 2.0 license except for the following:

http://www.apache.org/licenses/LICENSE-2.0

"Subject to the terms and conditions of this License, each Contributor hereby grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable (except as stated in this section) patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer the Work, where such license applies only to those patent claims licensable by such Contributor that are necessarily infringed by their Contribution(s) alone or by combination of their Contribution(s) with the Work to which such Contribution(s) was submitted. If You institute patent litigation against any entity (including a cross-claim or counterclaim in a lawsuit) alleging that the Work or a Contribution incorporated within the Work constitutes direct or contributory patent infringement, then any patent licenses granted to You under this License for that Work shall terminate as of the date such litigation is filed."

https://opensource.org/licenses/ECL-2.0

Subject to the terms and conditions of this License, each Contributor hereby grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable (except as stated in this section) patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer the Work, where such license applies only to those patent claims licensable by such Contributor that are necessarily infringed by their Contribution(s) alone or by combination of their Contribution(s) with the Work to which such Contribution(s) was submitted. If You institute patent litigation against any entity (including a cross-claim or counterclaim in a lawsuit) alleging that the Work or a Contribution incorporated within the Work constitutes direct or contributory patent infringement, then any patent licenses granted to You under this License for that Work shall terminate as of the date such litigation is filed. **Any patent license granted hereby with respect to contributions by an individual employed by an institution or organization is
limited to patent claims where the individual that is the author of the Work is also the inventor of the patent claims licensed, and where the organization or institution has the right to grant such license under applicable grant and research funding agreements. No other express or implied licenses are granted.**"

Only Sakai, OAE are a few related projects use ECL 2.0.  In my exchanges with the Jack Bernard of the Tech Transfer office regarding the licensing of Problem Roulette, we both agreed the Apache 2.0 license or a BSD-style license such as the MIT license was appropriate for UMich open source projects.

**Comment by zqian** [comment]
Looks good to me!

**Comment by dlhaines** [comment]
The license issue is interesting, but I'm going to consider it as independent of this change.

**Pull request merged**
